# Khayt Server HTTP requests

## Create user

POST http://localhost:3000/user/sign-up
Content-Type: application/json

{
  "email": "abhaygoswami676@gmail.com",
  "username":"123",
  "name": "Nikk.xyz",
  "password": "123"
}

### Login
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "abhaygoswami676@gmail.com",
  "password": "123"
}

### Create Short URL
POST http://localhost:3000/url/create
Content-Type: application/json

{
  "longURL": "https://instagram.com",
  "isPasswordProtected": false
}

### Add URL to Fav.
PATCH   http://localhost:3000/url/1a2a5fd5-0741-40f5-86c3-11cc172f749f
Content-Type: application/json

{}